apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-mq
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/orion-hub/routex-hub-deployment-config.git
    targetRevision: master
    path: argocd/ibm-mq
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true