apiVersion: v1
kind: Service
metadata:
  name: ibm-mq
  namespace: messaging
spec:
  type: ClusterIP
  selector:
    app: ibm-mq
  ports:
    - name: mq
      port: 1414
      targetPort: 1414
    - name: web
      port: 9443
      targetPort: 9443