apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "routex.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "routex.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "routex.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "routex.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "routex.serviceAccountName" . }}
      {{- end }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: {{ include "routex.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort | default 8080 }}

          env:
            {{- range .Values.env | default list }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}

            {{- range .Values.envFromSecret | default list }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .secretName | quote }}
                  key: {{ .key | quote }}
            {{- end }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
          {{- if eq (.Values.probes.readinessProbe.type | default "tcp") "tcp" }}
            tcpSocket:
              port: {{ .Values.probes.readinessProbe.port | default (.Values.containerPort | default 8080) }}
              {{- else }}
            httpGet:
              path: {{ .Values.probes.readinessProbe.httpGet.path | quote }}
              port: http
              {{- with .Values.probes.readinessProbe.httpGet.httpHeaders }}
              httpHeaders:
              {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- end }}
            periodSeconds: {{ .Values.probes.readinessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.probes.readinessProbe.timeoutSeconds | default 2 }}
            failureThreshold: {{ .Values.probes.readinessProbe.failureThreshold | default 12 }}
            successThreshold: {{ .Values.probes.readinessProbe.successThreshold | default 1 }}
            {{- if and .Values.probes .Values.probes.livenessProbe .Values.probes.livenessProbe.enabled }}
          livenessProbe:
          {{- if eq (.Values.probes.livenessProbe.type | default "tcp") "tcp" }}
            tcpSocket:
              port: {{ .Values.probes.livenessProbe.port | default (.Values.containerPort | default 8080) }}
                    {{- else }}
            httpGet:
              path: {{ .Values.probes.livenessProbe.httpGet.path | quote }}
              port: http
              {{- with .Values.probes.livenessProbe.httpGet.httpHeaders }}
              httpHeaders:
              {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- end }}
            periodSeconds: {{ .Values.probes.livenessProbe.periodSeconds | default 20 }}
            timeoutSeconds: {{ .Values.probes.livenessProbe.timeoutSeconds | default 2 }}
            failureThreshold: {{ .Values.probes.livenessProbe.failureThreshold | default 6 }}
            successThreshold: {{ .Values.probes.livenessProbe.successThreshold | default 1 }}
            {{- end }}