apiVersion: v1
kind: Service
metadata:
  name: {{ include "routex.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "routex.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: {{ include "routex.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 80 }}
      targetPort: http