apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://gitlab.com/orion-hub/routex-hub-deployment-config.git
    targetRevision: master
    path: argocd
    helm:
      valueFiles:
        - jenkins/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true