apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: routex-hub-user-service-production
  namespace: argocd
  labels:
    app: routex-hub-user-service
    env: production
spec:
  project: default

  source:
    repoURL: https://gitlab.com/orion-hub/routex-hub-deployment-config.git
    targetRevision: master
    path: deployment-config
    helm:
      releaseName: routex-user-service-production
      valueFiles:
        - service/routex-hub-user-service/values-production.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: orion-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true