apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-dev
  namespace: orion-dev
spec:
  project: default

  source:
    repoURL: https://gitlab.com/orion-hub/routex-hub-deployment-config.git
    targetRevision: master
    path: deployment-config
    helm:
      releaseName: postgresql-dev
      valueFiles:
        - service/routex-hub-driver-service/values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: orion-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true