apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-service-dev
  namespace: orion-hub-argocd
spec:
  project: default

  sources:
    - repoURL: https://gitlab.com/orion-hub/orion-hub-deployment-config.git
      targetRevision: master
      path: deployment-config/orion-hub-helm-chart
      helm:
        valueFiles:
          - service/orion-hub-product-service/values-dev.yaml
          -
    - repoURL: https://gitlab.com/orion-hub/orion-hub-deployment-configs.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true