apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-service-dev
  namespace: orion-hub-argocd
spec:
  project: default

  source:
    repoURL: https://gitlab.com/orion-hub/deployment-configs.git
    targetRevision: main
    path: charts/spring-boot-app
    helm:
      valueFiles:
        - environments/dev/product-service.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true