apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "orion-hub-helm-chart.fullname" . }}
  labels:
    {{- include "orion-hub-helm-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "orion-hub-helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "orion-hub-helm-chart.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "orion-hub-helm-chart.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.spring.profile | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "orion-hub-helm-chart.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 30
            periodSeconds: 20