apiVersion: v1
kind: Service
metadata:
  name: {{ include "orion-hub-helm-chart.fullname" . }}
  labels:
    {{- include "orion-hub-helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "orion-hub-helm-chart.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}